### ISSUE TITLE
todo: unit tets and CI setup (Travis CI)

### ISSUE THREAD

**Issue by DanielRuf** [ines/spacy-js#1]
I think we need some unit tests.
How could they look like and which testing library/ies should we use?

**Comment by ines** [comment]
Yessss! Sorry about the lack of test. I also have to admit, I'm kinda bad at testing JavaScript 😛

>  How could they look like and which testing library/ies should we use?

[Jest](https://jestjs.io/) is nice, we use that for another project. I think we could also get away with only mocking up `Language.makeDoc` and replacing it with a function that returns static `{ words, spaces, attrs }`. We can then test the rest accordingly, because nothing else relies on the REST API anymore (except for the `similarity` methods, which aren't even documented yet).

**Comment by ines** [comment]
Started with Python tests: https://github.com/ines/spacy-js/tree/master/tests 🎉

**Comment by ines** [comment]
Travis done and passing for both Python and JavaScript 🎉
https://travis-ci.org/ines/spacy-js

I thought this would be more frustrating to set up, but turned out to work quite smoothly. I'm sure there's still a lot of room for improvement in terms of JS testing and I'm always open for suggestions!
